{% if not other_environment %}name: {{ otter_env_name }}
channels:
    - defaults
    - conda-forge
dependencies:
    - python={{ python_version }}
    - pip
    - jupyter_server    
    - nb_conda_kernels
    - jupyter_server    
    - pip:
        - -r requirements.txt{% else %}{{ other_environment }}{% endif %}